### ISSUE TITLE
As a staff user I should be able to see quotas per organization

### ISSUE THREAD

**Issue by mustela** [datum-cloud/staff-portal#49]
### Overview

Implement a quota usage dashboard in the staff portal that displays real-time quota consumption for organizations using AllowanceBuckets and provides a streamlined workflow for increasing quota limits by creating or updating ResourceGrants.

### User Story

As a staff user, I need to:

- View detailed quota usage and limits for any organization
- Quickly identify when organizations are approaching quota limits
- Efficiently increase quota limits without navigating away from the usage dashboard

### API Integration

Primary Resource - [AllowanceBucket](https://github.com/datum-cloud/milo/blob/feature/quota-api-surface/docs/api/quota.md#allowancebucket)

The quota system automatically creates AllowanceBucket resources that aggregate quota capacity and consumption for each (consumer, resourceType) combination.

Secondary Resource - [ResourceGrant](https://github.com/datum-cloud/milo/blob/feature/quota-api-surface/docs/api/quota.md#resourcegrant)

To increase quotas, create or update ResourceGrant resources:

```yaml
apiVersion: quota.miloapiservice.com/v1alpha1
kind: ResourceGrant
spec:
  consumerRef:
    kind: Organization
    name: "acme-corp"
  allowances:
    - resourceType: "resourcemanager.miloapiservice.com/projects"
      buckets:
        - amount: 100
```

> [!IMPORTANT]
>
> Grants with the label `quota.miloapis.com/auto-created: "true"` are automatically managed by the quota system based on GrantCreationPolicies that are configured in the system. Do **not** modify resource grants with this label because any changes will automatically be reverted by the system.

### Display Fields

- `Name`: `spec.resourceTypeName`
  - Derived
  - Example: `resourcemanager.miloapis.com/Project` --> `Projects`
- `Description`: `spec.resourceTypeName`
  - Derived
  - Example: `resourcemanager.miloapis.com/Project` --> `Maximum projects for the organization`
- `TotalLimit`: `status.totalLimit`
  - Direct
- `Used`: `status.totalAllocated`
  - Direct
- `Available`: `status.available`
  - Direct
- `Percentage Used` and progress bar: `status.totalAllocated / status.totalLimit * 100`
  - Calculated
  - Example: `8 / 15 * 100 = 53.3%`
